name: dsi-sg
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bokeh
  - flask
  - gensim
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - lxml
  - nltk
  - notebook
  - pip
  - psycopg2
  - opencv
  - pyopengl
  - pymc3
  - python=3.8
  - requests
  - scikit-learn
  - seaborn
  - sqlalchemy
  - statsmodels
  - transformers
  - pip:
    - tensorflow
    - mlflow
    - streamlit
